SMS/Models/ScheduleInformation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SMS.Models
{
    public partial class ScheduleInformation
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long ShScheduleId { get; set; }
        public long RmRoomId { get; set; }
        public string ShClass { get; set; }
        public string ShDay { get; set; }
        //public string ShFromTime { get; set; }
        //public string ShToTime { get; set; }
        public DateTime? ShFromTime { get; set; }
        public DateTime? ShToTime { get; set; }
        public string ShCourse { get; set; }
        public string ShSection { get; set; }
        public string Year { get; set; }
        [ForeignKey("RmRoomId")]
        public virtual RoomInformation RoomInformation { get; set; }
    }
}

SMS/Controllers/ScheduleInformationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SMS.Models;
using SMS.ViewModels;

namespace SMS.Controllers
{
    public class ScheduleInformationController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ScheduleInformation
        public ActionResult Index(string classId)
        {
            ViewBag.ClassId = new SelectList(db.ClassOrYears,"Code","Name");
            var scheduleInformations = db.ScheduleInformations.Include(s => s.RoomInformation);
            return View(scheduleInformations.Where(s => s.ShClass == classId).ToList());
        }

        // GET: ScheduleInformation/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ScheduleInformation scheduleInformation = db.ScheduleInformations.Find(id);
            if (scheduleInformation == null)
            {
                return HttpNotFound();
            }
            return View(scheduleInformation);
        }

        // GET: ScheduleInformation/Create
        public ActionResult Create(string classId)
        {
            ViewSchedule objViewSchedule = new ViewSchedule();
            List<ViewScheduleInformation> objScheduleInformation = new List<ViewScheduleInformation>();
            objViewSchedule.ClassId = new SelectList(db.ClassOrYears, "Code", "Name", classId);
            ViewBag.RmRoomId = new SelectList(db.RoomInformations, "RmRoomId", "RmRoomNo");
            objViewSchedule.RoomInformation = db.RoomInformations.ToList();

            if (String.IsNullOrEmpty(classId))
            //if (classId == null || classId == "")
            {
                var schedule = db.ScheduleInformations.Where(w => w.ShClass == classId).Select(s => new { s.ShFromTime, s.ShToTime }).Distinct().ToList();
                foreach (var item in schedule)
                {
                    objScheduleInformation.Add(new ViewScheduleInformation());
                    objScheduleInformation[objScheduleInformation.Count - 1].ShFromTime = item.ShFromTime.GetValueOrDefault();
                    objScheduleInformation[objScheduleInformation.Count - 1].ShToTime = item.ShToTime.GetValueOrDefault();

                }
            }
            else
            {
                var sc = (from S in db.ScheduleInformations
                    where S.ShClass == classId
                    select new
                    {
                        fromTime = S.ShFromTime,
                        toTime = S.ShToTime
                    }).Distinct().ToList();
                //var schedule = db.ScheduleInformations.Where(w => w.ShClass == classId).Select(s => new { s.ShFromTime, s.ShToTime }).Distinct().ToList();
                foreach (var item in sc)
                {
                    objScheduleInformation.Add(new ViewScheduleInformation());
                    objScheduleInformation[objScheduleInformation.Count - 1].ShFromTime = item.fromTime.GetValueOrDefault();
                    objScheduleInformation[objScheduleInformation.Count - 1].ShToTime = item.toTime.GetValueOrDefault();
                }
            }
            objViewSchedule.ScheduleInformation = objScheduleInformation;

            return View(objViewSchedule);
        }

        // POST: ScheduleInformation/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "ShScheduleId,RmRoomId,ShClass,ShDay,ShFromTime,ShToTime,ShCourse,ShSection")] ScheduleInformation scheduleInformation)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.ScheduleInformations.Add(scheduleInformation);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    ViewBag.RmRoomId = new SelectList(db.RoomInformations, "RmRoomId", "RmRoomNo", scheduleInformation.RmRoomId);
        //    return View(scheduleInformation);
        //}





        //[HttpPost]
        //[ValidateAntiForgeryToken]
         [HttpPost, ActionName("Create")]
        public ActionResult Create(string roomId, string day, string time, string classId)
        {
            ScheduleInformation scheduleinformation = new ScheduleInformation();
            var date = time.Split('-');
            var rMRoomId = Convert.ToInt64(roomId);
            var sHFromTime = Convert.ToDateTime(date[0]);
            var sHToTime = Convert.ToDateTime(date[1]);
            var dpRoom  = db.ScheduleInformations.Where(w => w.RmRoomId == rMRoomId && w.ShDay == day &&
                                             (w.ShFromTime >= sHFromTime && w.ShToTime <= sHToTime)).ToList();

            var data = db.ScheduleInformations.Where(w => w.RmRoomId == rMRoomId && w.ShDay == day && w.ShClass == classId &&
                                               (w.ShFromTime >= sHFromTime && w.ShToTime <= sHToTime)).ToList();
            if (data.Count == 0 && dpRoom.Count == 0)
            {
                var year = DateTime.Now.Year;

                scheduleinformation.RmRoomId = Convert.ToInt64(roomId);
                scheduleinformation.ShDay = day;
                scheduleinformation.ShFromTime = Convert.ToDateTime(date[0]);
                scheduleinformation.ShToTime = Convert.ToDateTime(date[1]);
                scheduleinformation.ShClass = classId;
                scheduleinformation.Year = Convert.ToString(year);
                db.ScheduleInformations.Add(scheduleinformation);
                db.SaveChanges();

            }
            return Json(new { result = "success" }, JsonRequestBehavior.AllowGet);
        }

        // GET: ScheduleInformation/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ScheduleInformation scheduleInformation = db.ScheduleInformations.Find(id);
            if (scheduleInformation == null)
            {
                return HttpNotFound();
            }
            ViewBag.RmRoomId = new SelectList(db.RoomInformations, "RmRoomId", "RmRoomNo", scheduleInformation.RmRoomId);
            return View(scheduleInformation);
        }

        // POST: ScheduleInformation/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ShScheduleId,RmRoomId,ShClass,ShDay,ShFromTime,ShToTime,ShCourse,ShSection")] ScheduleInformation scheduleInformation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(scheduleInformation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.RmRoomId = new SelectList(db.RoomInformations, "RmRoomId", "RmRoomNo", scheduleInformation.RmRoomId);
            return View(scheduleInformation);
        }

        // GET: ScheduleInformation/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ScheduleInformation scheduleInformation = db.ScheduleInformations.Find(id);
            if (scheduleInformation == null)
            {
                return HttpNotFound();
            }
            return View(scheduleInformation);
        }

        // POST: ScheduleInformation/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            ScheduleInformation scheduleInformation = db.ScheduleInformations.Find(id);
            db.ScheduleInformations.Remove(scheduleInformation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SMS/Views/ScheduleInformation/Delete.cshtml
@model SMS.Models.ScheduleInformation

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ScheduleInformation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RoomInformation.RmRoomNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoomInformation.RmRoomNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShClass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShClass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShFromTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShFromTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShToTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShToTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShCourse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShCourse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShSection)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShSection)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SMS/Views/ScheduleInformation/Details.cshtml
@model SMS.Models.ScheduleInformation

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ScheduleInformation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RoomInformation.RmRoomNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoomInformation.RmRoomNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShClass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShClass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShFromTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShFromTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShToTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShToTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShCourse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShCourse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShSection)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShSection)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ShScheduleId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SMS/Views/ScheduleInformation/Edit.cshtml
@model SMS.Models.ScheduleInformation

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ScheduleInformation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ShScheduleId)

        <div class="form-group">
            @Html.LabelFor(model => model.RmRoomId, "RmRoomId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RmRoomId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RmRoomId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShClass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShClass, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShClass, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShFromTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShFromTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShFromTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShToTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShToTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShToTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShCourse, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShCourse, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShCourse, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShSection, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShSection, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShSection, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SMS/Views/ScheduleInformation/Index.cshtml
@using System.Globalization
@model IEnumerable<SMS.Models.ScheduleInformation>

@{
    ViewBag.Title = "Index";
}

<h2>Schedule Information </h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>


@using (Html.BeginForm("Index", "ScheduleInformation", FormMethod.Get))
{
    <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="form-group">
            <label id="Campus" class="col-md-1 control-label">Class</label>
            <div class="col-md-2">
                @Html.DropDownList("ClassId", null, htmlAttributes: new { @class = "form-control" })
            </div>
            <div class="col-md-1">
                <input type="submit" value="Load" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div class="col-sm-12 col-md-12 col-lg-12 " style=" padding:20px;">
    <table class="table table-striped table-bordered table-hover dataTable dtr-inline" data-page-length='10' id="T1">
        <thead>
            <tr>
               
                <th>
                    @Html.DisplayName("Class")
                </th>
                <th>
                    @Html.DisplayName("Course")
                </th>
                <th>
                    @Html.DisplayName("Section")
                </th>
                <th>
                    @Html.DisplayName("Day")
                </th>
                <th>
                    @Html.DisplayName("Room No")
                </th>
                <th>
                    @Html.DisplayName("From Time")
                </th>
                <th>
                    @Html.DisplayName("To Time")
                </th>
               
                @*<th></th>*@
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>

                    <td>
                        @Html.DisplayFor(modelItem => item.ShClass)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ShCourse)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ShSection)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ShDay)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RoomInformation.RmRoomNo)
                    </td>
                    <td>
                        @{
                var fromTime = item.ShFromTime != null ? item.ShFromTime.Value.ToString("h:mm tt", CultureInfo.CreateSpecificCulture("en-BD")) : "";
                        }
                        @fromTime
                    </td>
                    <td>
                        @{
                var toTime = item.ShToTime != null ? item.ShToTime.Value.ToString("h:mm tt", CultureInfo.CreateSpecificCulture("en-BD")) : "";
                        }
                        @toTime

                    </td>
                   
                    @*<td>
                            @Html.ActionLink("Delete", "Delete", new { id = item.ShScheduleId })
                        </td>*@
                </tr>
            }
        </tbody>
    </table>

</div>




@section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
            <script type="text/javascript">
                $(document).ready(function () {
                    $('#T1').DataTable({
                        "order": [[0, "desc"]]
                    });
                });


            </script>
        }